"""Minimal CPU classification predictor intended for use from FastAPI.

The class map MUST come from the training ImageFolder.class_to_idx output.
Never assume the order of disease names or silently load random weights.
"""

import json
from pathlib import Path

import timm
import torch
from PIL import Image, UnidentifiedImageError

from .preprocess import build_transform


def load_class_names(class_map_path):
    """Read training's class_to_idx.json, validating a contiguous 0-based mapping."""
    path = Path(class_map_path)
    with path.open("r", encoding="utf-8") as file:
        mapping = json.load(file)
    if not isinstance(mapping, dict) or not mapping:
        raise ValueError("class_to_idx must be a non-empty JSON object")
    if any(not isinstance(name, str) or not isinstance(index, int) or isinstance(index, bool)
           for name, index in mapping.items()):
        raise ValueError("class_to_idx must map class-name strings to integer indices")
    if sorted(mapping.values()) != list(range(len(mapping))):
        raise ValueError("class_to_idx indices must be unique and consecutive from zero")
    names = [None] * len(mapping)
    for name, index in mapping.items():
        names[index] = name
    return names


class PlantDiseasePredictor:
    def __init__(
        self,
        checkpoint_path,
        class_map_path,
        model_name="mobilenetv3_small_100",
        model_version="unversioned",
        image_size=224,
        device="cpu",
    ):
        self.device = torch.device(device)
        self.model_version = model_version
        self.class_names = load_class_names(class_map_path)
        self.transform = build_transform(image_size)
        path = Path(checkpoint_path)
        if not path.is_file():
            raise FileNotFoundError(f"Missing model checkpoint: {path}")
        self.model = timm.create_model(
            model_name, pretrained=False, num_classes=len(self.class_names)
        )
        # State dict generated by training scripts; refuse incompatible checkpoints.
        weights = torch.load(path, map_location="cpu", weights_only=True)
        if isinstance(weights, dict) and "model" in weights:
            weights = weights["model"]
        elif isinstance(weights, dict) and "state_dict" in weights:
            weights = weights["state_dict"]
        if not isinstance(weights, dict):
            raise ValueError("Checkpoint does not contain a state dict")
        self.model.load_state_dict(weights, strict=True)
        self.model.to(self.device)
        self.model.eval()

    def predict(self, image, top_k=3):
        """Predict PIL Image or image path. Returns JSON-serializable top-k results."""
        if not 1 <= top_k <= len(self.class_names):
            raise ValueError(f"top_k must be between 1 and {len(self.class_names)}")
        try:
            if isinstance(image, (str, Path)):
                with Image.open(image) as im:
                    rgb = im.convert("RGB")
            elif isinstance(image, Image.Image):
                rgb = image.convert("RGB")
            else:
                raise TypeError("image must be a PIL Image or image file path")
        except (UnidentifiedImageError, OSError) as exc:
            raise ValueError("Invalid or unreadable image") from exc

        tensor = self.transform(rgb).unsqueeze(0).to(self.device)
        with torch.inference_mode():
            logits = self.model(tensor)
            if logits.ndim != 2 or logits.shape != (1, len(self.class_names)):
                raise RuntimeError(f"Unexpected output shape: {tuple(logits.shape)}")
            probs = torch.softmax(logits, dim=1)[0]
            values, indices = torch.topk(probs, k=top_k)
        return {
            "model_version": self.model_version,
            "predictions": [
                {"class_id": int(idx), "label": self.class_names[int(idx)],
                 "confidence": float(score)}
                for score, idx in zip(values.tolist(), indices.tolist())
            ],
        }
